### ISSUE TITLE
"ISSUEベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by UNNNYOU** [UNNNYOU/otsumami-online#4]
## 概要
ISSUEが作成が問題なく行われているかのレビューしていただくためのISSUEです。
実装予定のタスクをMVPリリース時、本リリース時に分けて記載を行なってください。
また、必要ページの一覧も用意してください。

## MVPリリース時

- [x]  会員登録機能
- [x]  ログイン機能
- [x]  マイページ機能
- [x]  登録情報設定機能
- [x]  パスワード変更機能
- [x]  メールアドレス変更機能
- [x]  投稿機能（レビュー機能）
- [x]  投稿一覧機能（検索機能）
- [x]  投稿詳細機能
- [x]  投稿編集機能
- [x]  投稿削除機能
- [x]  周辺検索機能
- [x]  経路検索機能

##  本リリース時

- [x]  タグ設定機能
- [x]  タグ検索機能
- [x]  いいね機能
- [x]  ブックマーク機能（お気に入り機能）
- [x]  マルチ検索
- [x]  オートコンプリート機能

## 必要ページ

- [x] トップページ
- [x] 会員登録ページ
- [x] ログインページ
- [x] マイページ
- [x] 登録情報設定ページ
- [x] パスワード再設定URL発行ページ
- [x] パスワード再設定ページ
- [x] メールアドレス再設定ページ
- [x] 投稿ページ
- [x] 投稿一覧ページ
- [x] 投稿詳細ページ
- [x] 投稿編集ページ
- [x] 周辺検索ページ
- [x] ブックマークページ
- [x] 利用規約ページ
- [x] プライバシーポリシーページ
- [x] 問い合わせページ

**Comment by kenchasonakai** [comment]
LGTMです！
