### ISSUE TITLE
MVPリリースレビュー依頼

### ISSUE THREAD

**Issue by UNNNYOU** [UNNNYOU/otsumami-online#80]
## 各種情報
サービス名 おつまみオンライン
サービスURL https://otsumami-online.onrender.com/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
以下、READMEレビュー時にMVPリリース時点で実装予定のものです。
READMEレビュー時点ではかなり抽象的でしたので詳細にしております。

- ユーザー機能
  - [x]  会員登録機能
  - [x]  ログイン機能
  - [x]  マイページ機能
  - [ ]  登録情報設定機能
  - [ ]  パスワード変更機能
  - [ ]  メールアドレス変更機能

- 投稿機能
  - [x]  投稿機能（レビュー機能）※ヘッダーから画面遷移が可能
  - [x]  投稿一覧機能（検索機能）
    - [x] ヘッダーにて検索を可能にし、画面遷移（都道府県、おつまみの名称、レビュー本文にて検索）
    - [x] 検索結果画面にてソート機能の実装
  - [x]  投稿詳細機能　※投稿一覧画面、周辺検索画面から画面遷移が可能
  - [x]  投稿編集機能　※マイページにて画面遷移が可能  
  - [x]  投稿削除機能　※マイページにて画面遷移が可能 
  - [x]  周辺検索機能　※トップページ、ログイン後のハンバーガーから画面遷移が可能 
  - [ ]  経路検索機能

## READMEレビュー時から変更した機能
MVP面談の際に基本的な機能以外は省こうというお話になったので、以下の機能は本リリース時に作成します。

MVP面談時に省くことになったもの
- [ ]  登録情報設定機能
- [ ]  パスワード変更機能
- [ ]  メールアドレス変更機能

実装中に本リリース時でも良いと思い、実装しなかったもの
- [ ]  経路検索機能

## サービスイメージがわかるようなスクリーンショット等

|トップ画面 | 投稿機能 |
| --- | --- |
| <img alt="トップ画面" width="350px" src="https://i.gyazo.com/23c095df52bef38dd84357018a86af9b.gif"> | <img alt="検索結果" width="350px" src="https://i.gyazo.com/a9b5a8c5f940875b2e34fccc02ca5dd0.gif"> |

| 周辺検索 | 検索機能 |
| --- | --- | 
| <img alt="" width="350px" src="https://i.gyazo.com/dab37b5e81f5a5cce0d1c8eae545f2b9.gif"> | <img alt="" width="350px" src="https://i.gyazo.com/510db4b1d3b925df0c51b8365a6b88df.gif"> |

**Comment by tarakish** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。
